name: silvertime
description: Silvertime Mobile App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_scroll_text: ^0.0.6
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.3
  email_validator: ^2.1.17
  extended_tabs: ^4.0.2
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.1
  flutter_launcher_icons: ^0.12.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^7.1.4
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_sticky_header: ^0.6.5
  flutter_work_utils: ^0.0.2
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  http_request_utils: ^0.2.8
  image_picker: ^0.8.7+2
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  lottie: ^2.3.2
  page_transition: ^2.0.9
  provider: ^6.0.5
  searchfield: ^0.6.9
  shared_preferences: ^2.0.20
  skeletons: ^0.0.3
  smooth_page_indicator: ^1.0.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/logos/
    - assets/tutorial/

flutter_intl:
  enabled: true
